---
####################################################################
## Ulimit Config
####################################################################

- block:

  - name: "Setting ulimits for Viya - in /etc/security/limits.conf"
    become: yes
    become_user: root
    pam_limits:
      # dest: "{{ulimit_file_loc}}"
      domain: "{{item.domain}}"
      limit_type: "{{item.type}}"
      limit_item: "{{item.item}}"
      value: "{{item.value}}"
      use_max: "{{item.use_max}}"
      use_min: "{{item.use_min}}"
      comment: "{{item.comment}}"
      backup: yes
    with_items:
      - "{{ulimits}}"

  - name: Gather the current Ulimit values for user {{sas_user}} and root
    become: yes
    become_user: "{{item}}"
    shell: ulimit -a
    changed_when: False
    check_mode: no
    register: review_ulimits
    with_items:
      - "{{sas_user}}"
      - root
  - debug: var=review_ulimits

  ## block end
  tags:
    - ulimit_config
